SELECT p.ID, p.CLIENT_ID, c."NAME" AS CLIENT_NAME, p.START_DATE, p.FINISH_DATE,
       SUM(w.SALARY) * EXTRACT(MONTH FROM AGE(p.FINISH_DATE, p.START_DATE)) AS PRICE
FROM project p
JOIN project_worker pw ON p.ID = pw.PROJECT_ID
JOIN worker w ON pw.WORKER_ID = w.ID
JOIN client c ON p.CLIENT_ID = c.ID
GROUP BY p.ID, c."NAME", p.CLIENT_ID, p.START_DATE, p.FINISH_DATE
ORDER BY PRICE DESC;